package main

import (
	"strings"
)

// countryColos maps ISO 3166-1 alpha-2 country codes to Cloudflare colo
// codes. CFST matches Cloudflare's cf-ray value by colo, so country aliases
// must be expanded before -cfcolo is passed to the engine.
var countryColos = map[string][]string{
	"AE": {"DXB"},
	"AL": {"TIA"},
	"AM": {"EVN"},
	"AO": {"LAD"},
	"AR": {"COR", "EZE", "NQN"},
	"AT": {"VIE"},
	"AU": {"ADL", "BNE", "CBR", "HBA", "MEL", "PER", "SYD"},
	"AZ": {"GYD", "LLK"},
	"BB": {"BGI"},
	"BD": {"CGP", "DAC"},
	"BE": {"BRU"},
	"BF": {"OUA"},
	"BG": {"SOF"},
	"BH": {"BAH"},
	"BN": {"BWN"},
	"BO": {"LPB"},
	"BR": {"ARU", "BEL", "BSB", "CAW", "CFC", "CGB", "CNF", "CWB", "FLN", "FOR", "GIG", "GRU", "GYN", "JDO", "JOI", "MAO", "NVT", "PMW", "POA", "QWJ", "RAO", "REC", "SJK", "SJP", "SOD", "SSA", "UDI", "VCP", "VIX", "XAP"},
	"BT": {"PBH"},
	"BW": {"GBE"},
	"BY": {"MSQ"},
	"CA": {"YHZ", "YUL", "YVR", "YWG", "YXE", "YYC", "YYZ"},
	"CD": {"FIH"},
	"CH": {"GVA", "ZRH"},
	"CI": {"ABJ", "ASK"},
	"CL": {"ARI", "SCL"},
	"CM": {"DLA"},
	"CN": {"ACX", "AVA", "CAN", "CGD", "CGO", "CKG", "CSX", "CTU", "CZX", "DLC", "FOC", "FUO", "HAK", "HGH", "HYN", "JXG", "KHN", "KMG", "KWE", "LHW", "LYA", "PKX", "SHA", "SJW", "SZX", "TAO", "TEN", "TNA", "TYN", "XFN", "XIY"},
	"CO": {"BAQ", "BOG", "CLO", "MDE"},
	"CR": {"SJO"},
	"CY": {"LCA"},
	"CZ": {"PRG"},
	"DE": {"DUS", "FRA", "HAM", "MUC", "STR", "TXL"},
	"DJ": {"JIB"},
	"DK": {"CPH"},
	"DO": {"SDQ", "STI"},
	"DZ": {"AAE", "ALG", "CZL", "ORN"},
	"EC": {"GYE", "UIO"},
	"EE": {"TLL"},
	"EG": {"CAI"},
	"ES": {"BCN", "MAD"},
	"ET": {"ADD"},
	"FI": {"HEL"},
	"FJ": {"SUV"},
	"FR": {"BOD", "CDG", "LYS", "MRS"},
	"GB": {"LHR", "MAN"},
	"GD": {"GND"},
	"GE": {"TBS"},
	"GH": {"ACC"},
	"GR": {"ATH", "SKG"},
	"GT": {"GUA"},
	"GU": {"GUM"},
	"GY": {"GEO"},
	"HK": {"HKG"},
	"HN": {"SAP", "TGU"},
	"HR": {"ZAG"},
	"HU": {"BUD"},
	"ID": {"CGK", "DPS", "JOG", "MLG"},
	"IE": {"DUB"},
	"IL": {"HFA", "TLV"},
	"IN": {"AGR", "AIP", "AMD", "BBI", "BDQ", "BLR", "BOM", "CCU", "CJB", "CNN", "COK", "DEL", "HYD", "IXC", "JRG", "KNU", "LUH", "MAA", "NAG", "PAT", "PNQ", "UDR"},
	"IQ": {"BGW", "BSR", "EBL", "ISU", "NJF", "XNH"},
	"IS": {"KEF"},
	"IT": {"FCO", "MXP", "PMO"},
	"JM": {"KIN"},
	"JO": {"AMM"},
	"JP": {"FUK", "KIX", "NRT", "OKA"},
	"KE": {"MBA", "NBO"},
	"KG": {"FRU"},
	"KH": {"PNH"},
	"KR": {"ICN"},
	"KW": {"KWI"},
	"KZ": {"AKX", "ALA", "NQZ"},
	"LA": {"VTE"},
	"LB": {"BEY"},
	"LK": {"CMB"},
	"LT": {"VNO"},
	"LU": {"LUX"},
	"LV": {"RIX"},
	"MD": {"KIV"},
	"MG": {"TNR"},
	"MK": {"SKP"},
	"MN": {"ULN"},
	"MO": {"MFM"},
	"MT": {"MLA"},
	"MU": {"MRU"},
	"MV": {"MLE"},
	"MW": {"LLW"},
	"MX": {"GDL", "MEX", "QRO"},
	"MY": {"JHB", "KCH", "KUL"},
	"MZ": {"MPM"},
	"NA": {"WDH"},
	"NC": {"NOU"},
	"NG": {"LOS"},
	"NL": {"AMS"},
	"NO": {"OSL"},
	"NP": {"KTM"},
	"NZ": {"AKL", "CHC", "WLG"},
	"OM": {"MCT"},
	"PA": {"PTY"},
	"PE": {"LIM"},
	"PF": {"PPT"},
	"PH": {"CEB", "CGY", "CRK", "MNL"},
	"PK": {"ISB", "KHI", "LHE"},
	"PL": {"WAW", "WRO"},
	"PR": {"SJU"},
	"PS": {"ZDM"},
	"PT": {"LIS"},
	"PY": {"ASU"},
	"QA": {"DOH"},
	"RE": {"RUN"},
	"RO": {"OTP"},
	"RS": {"BEG"},
	"RU": {"DME", "LED"},
	"RW": {"KGL"},
	"SA": {"DMM", "JED", "RUH"},
	"SE": {"ARN", "GOT"},
	"SG": {"SIN"},
	"SI": {"LJU"},
	"SK": {"BTS"},
	"SN": {"DKR"},
	"SR": {"PBM"},
	"TH": {"BKK", "CNX", "URT"},
	"TJ": {"DYU"},
	"TN": {"TUN"},
	"TR": {"ADB", "IST"},
	"TT": {"POS"},
	"TW": {"KHH", "TPE"},
	"TZ": {"DAR"},
	"UA": {"KBP"},
	"UG": {"EBB"},
	"US": {"ABQ", "ANC", "ATL", "AUS", "BGR", "BNA", "BOS", "BUF", "CLE", "CLT", "CMH", "CVG", "DEN", "DFW", "DTW", "EWR", "FSD", "HNL", "IAD", "IAH", "IND", "JAX", "JFK", "LAS", "LAX", "MCI", "MEM", "MIA", "MSP", "OKC", "OMA", "ORD", "ORF", "PDX", "PHL", "PHX", "PIT", "RDU", "RIC", "SAN", "SAT", "SEA", "SFO", "SJC", "SLC", "SMF", "STL", "TLH", "TPA"},
	"VN": {"DAD", "HAN", "SGN"},
	"ZA": {"CPT", "DUR", "JNB"},
	"ZM": {"LUN"},
	"ZW": {"HRE"},
}

func expandColoFilter(region string) string {
	code := strings.ToUpper(strings.TrimSpace(region))
	if colos, ok := countryColos[code]; ok {
		return strings.Join(colos, ",")
	}
	return code
}
